src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 55)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_time = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $picture = null;

    #[ORM\Column]
    private ?int $capacity = null;

    #[ORM\Column(length: 60)]
    private ?string $email = null;

    #[ORM\Column]
    private ?int $phone = null;

    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[ORM\Column(length: 255)]
    private ?string $url = null;

    #[ORM\Column(length: 60)]
    private ?string $type = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDateTime(): ?\DateTimeInterface
    {
        return $this->date_time;
    }

    public function setDateTime(\DateTimeInterface $date_time): self
    {
        $this->date_time = $date_time;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(int $capacity): self
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->phone;
    }

    public function setPhone(int $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }
}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;


class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, ["attr"=>["placeholder"=>"Type the name", "class"=>" w-50 form-control mb-2 text-center"]])
            ->add('date_time', DateTimeType::class, ["attr"=>[ "class"=>"w-50 form-control mb-2 text-center" ]])
            ->add('description', TextareaType::class,["attr"=>["placeholder"=>"Type description", "class"=>"w-50 form-control mb-2 text-center", "id"=>"name"]])
            ->add('picture', TextType::class, ["attr"=>["placeholder"=>"Type URL of a picture", "class"=>"w-50 form-control mb-2 text-center"]])
            ->add('capacity', TextType::class, ["attr"=>["placeholder"=>"Type capacity", "class"=>"w-50 form-control mb-2 text-center"]])
            ->add('email', TextType::class, ["attr"=>["placeholder"=>"Type email", "class"=>"w-50 form-control mb-2 text-center" ]])
            ->add('phone', IntegerType::class, ["attr"=>["placeholder"=>"Type phone", "class"=>"w-50 form-control mb-2 text-center" ]])
            ->add('address', TextType::class, ["attr"=>["placeholder"=>"Type the address", "class"=>"w-50 form-control mb-2 text-center"]])
            ->add('url', TextType::class, ["attr"=>["placeholder"=>"Type the URL of an event", "class"=>"w-50 form-control mb-2 text-center"]])
            ->add('type', ChoiceType::class,[
                'choices'  => [
                    'music' => "music",
                    'sport' => "sport",
                    'social' => "social"
                ]
                , "attr"=> ["class"=>"form-control w-50 text-center"]]
                )
                ;
            }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Form\EventType;
use App\Repository\EventRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class EventController extends AbstractController
{
    #[Route('/', name: 'app_event_index', methods: ['GET'])]
    public function index(EventRepository $eventRepository): Response
    {
        return $this->render('event/index.html.twig', [
            'events' => $eventRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_event_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EventRepository $eventRepository): Response
    {
        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $eventRepository->save($event, true);

            return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('event/new.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_event_show', methods: ['GET'])]
    public function show(Event $event): Response
    {
        return $this->render('event/show.html.twig', [
            'event' => $event,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_event_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Event $event, EventRepository $eventRepository): Response
    {
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $eventRepository->save($event, true);

            return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('event/edit.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_event_delete', methods: ['POST'])]
    public function delete(Request $request, Event $event, EventRepository $eventRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$event->getId(), $request->request->get('_token'))) {
            $eventRepository->remove($event, true);
        }

        return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
        <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    </head>
    <body style="background-image: url(https://img.redbull.com/images/c_limit,w_1500,h_1000,f_auto,q_auto/redbullcom/2019/07/16/288c17ef-e1c4-489b-9d59-4f550745f675/nova-rock-festival); background-repeat: no-repeat; background-size:100% 100%; opacity:0.9; ">
    <nav class="navbar navbar-expand-lg bg-dark m-3">
  <div class="container-fluid">
    <a class="navbar-brand text-white" href="/">Home</a>
    <h1 style="margin-right:38%" class="text-white">Best Event Page</h1>
    </div>
    <form class="d-flex" role="search">
        <button class="btn btn-success" type="submit"><a class="text-decoration-none text-white" href="{{ path('app_event_new') }}">Create new</a></button>
      </form>
</nav>
        {% block body %}{% endblock %}
        <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    </body>
</html>

templates/event/_delete_form.html.twig
<form method="post" action="{{ path('app_event_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/event/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/event/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Event{% endblock %}

{% block body %}
    <h1 class="text-center text-white">Edit Event</h1>
    <div style="width:50rem; padding-left:18%; border-radius:5%" class="container bg-dark">
    {{ include('event/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="text-decoration-none btn btn-warning" href="{{ path('app_event_index') }}">back to list</a>

    {{ include('event/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Events{% endblock %}

{% block body %}
    
    <div class="container d-flex justify-content-around"> 
       
    
            {% for event in events %}
            
            <div class="card" style="width: 18rem; ">
                <img src="{{ event.picture }}" class="card-img-top h-25" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ event.name }}</h5>
                    <p class="card-text">{{ event.description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{ event.dateTime ? event.dateTime|date('Y-m-d H:i:s') : '' }}</li>
                    <li class="list-group-item">{{ event.capacity }}</li>
                    <li class="list-group-item">{{ event.email }}</li>
                    <li class="list-group-item">{{ event.phone }}</li>
                    <li class="list-group-item">{{ event.address }}</li>
                   <a class="text-decoration-none" href="{{ event.url }}"><li class="list-group-item">Click on URL</li></a>
                    <li class="list-group-item">{{ event.type }}</li>
                </ul>
                <div class="card-body">
                    <a class="text-decoration-none btn btn-primary" href="{{ path('app_event_show', {'id': event.id}) }}" class="card-link ">Show</a>
                    <a class="text-decoration-none btn btn-warning" href="{{ path('app_event_edit', {'id': event.id}) }}" class="card-link">Edit</a>
                </div>
                </div>
                
                {% endfor %}
                
            
</div>
        

    
{% endblock %}

templates/event/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Event{% endblock %}

{% block body %}
    <h1 class="text-center text-white">Create new Event</h1>
    <div style="width:50rem; padding-left:18%; border-radius:5%" class="container bg-dark">
    {{ include('event/_form.html.twig') }}


    <a class="text-decoration-none btn btn-warning" href="{{ path('app_event_index') }}">back to list</a>
    </div>
{% endblock %}

templates/event/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event{% endblock %}

{% block body %}
    <h1 class="text-white text-center">Event</h1>
    <div class="container bg-dark">
    <table class="table">
        <tbody class="text-white">
            <tr >
                <th>Id</th>
                <td>{{ event.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ event.name }}</td>
            </tr>
            <tr>
                <th>Date_time</th>
                <td>{{ event.dateTime ? event.dateTime|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ event.description }}</td>
            </tr>
            <tr>
                <th>Picture</th>
                <td>{{ event.picture }}</td>
            </tr>
            <tr>
                <th>Capacity</th>
                <td>{{ event.capacity }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ event.email }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ event.phone }}</td>
            </tr>
            <tr>
                <th>Address</th>
                <td>{{ event.address }}</td>
            </tr>
            <tr>
                <th>Url</th>
                <td>{{ event.url }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ event.type }}</td>
            </tr>
        </tbody>
    </table>
    </div>
    <a class="text-decoration-none btn btn-primary" href="{{ path('app_event_index') }}">back to list</a>

    <a class="text-decoration-none btn btn-warning" href="{{ path('app_event_edit', {'id': event.id}) }}">edit</a>

    {{ include('event/_delete_form.html.twig') }}
{% endblock %}